// warp-drive-packages/react/src/-private/request.tsx
import {
  AutorefreshBehaviorCombos,
  createRequestSubscription,
  DISPOSE,
  RequestArgs,
  signal,
  type ContentFeatures,
  type RecoveryFeatures,
  type RequestLoadingState,
  type RequestState,
  type RequestSubscription,
} from "@warp-drive/core/store/-private";
import type { StructuredErrorDocument } from "@warp-drive/core/types/request";
import { JSX, ReactNode, useEffect, useMemo, useRef } from "react";
import { useStore } from "./store-provider";
import { ReactiveContext } from "./reactive-context";
import { SubscriptionArgs } from "@warp-drive/core/store/-private";
import { Future } from "@warp-drive/core/request";
import { StoreRequestInput } from "@warp-drive/core";

const IdleBlockMissingError = new Error(
  "No idle block provided for <Request> component, and no query or request was provided."
);

class ReactiveArgs<RT, E> implements SubscriptionArgs<RT, E> {
  @signal request?: Future<RT> | undefined | null;
  @signal query?: StoreRequestInput<RT> | undefined | null;
  @signal autorefresh?: AutorefreshBehaviorCombos | undefined;
  @signal autorefreshThreshold?: number | undefined;
  @signal autorefreshBehavior?: "refresh" | "reload" | "policy";
}

interface ChromeComponentProps<RT> {
  children: ReactNode;
  state: RequestState | null;
  features: ContentFeatures<RT>;
}

const DefaultChrome = <RT,>({ children }: ChromeComponentProps<RT>) => {
  return <>{children}</>;
};

export interface RequestProps<RT, E> extends RequestArgs<RT, E> {
  chrome?: React.FC<ChromeComponentProps<RT>>;

  states: RequestStates<RT, E>;
}

interface RequestStates<RT, E> {
  /**
   * The block to render when the component is idle and waiting to be given a request.
   *
   */
  idle?: React.FC<{}>;

  /**
   * The block to render when the request is loading.
   *
   */
  loading?: React.FC<{ state: RequestLoadingState }>;

  /**
   * The block to render when the request was cancelled.
   *
   */
  cancelled?: React.FC<{
    /**
     * The Error the request rejected with.
     */
    error: StructuredErrorDocument<E>;
    /**
     * Utilities to assist in recovering from the error.
     */
    features: RecoveryFeatures;
  }>;

  /**
   * The block to render when the request failed. If this block is not provided,
   * the error will be rethrown.
   *
   * Thus it is required to provide an error block and proper error handling if
   * you do not want the error to crash the application.
   */
  error: React.FC<{
    /**
     * The Error the request rejected with.
     */
    error: StructuredErrorDocument<E>;
    /**
     * Utilities to assist in recovering from the error.
     */
    features: RecoveryFeatures;
  }>;

  /**
   * The block to render when the request succeeded.
   *
   */
  content: React.FC<{ result: RT; features: ContentFeatures<RT> }>;
}

export function Throw({ error }: { error: Error }): never {
  throw error;
}

/**
 * The `<Request />` component is a powerful tool for managing data fetching and
 * state in your React application. It provides a declarative approach to reactive
 * control-flow for managing requests and state in your application.
 *
 * The `<Request />` component is ideal for handling "boundaries", outside which some
 * state is still allowed to be unresolved and within which it MUST be resolved.
 *
 * ## Request States
 *
 * `<Request />` has five states, only one of which will be active and rendered at a time.
 *
 * - `idle`: The component is waiting to be given a request to monitor
 * - `loading`: The request is in progress
 * - `error`: The request failed
 * - `content`: The request succeeded
 * - `cancelled`: The request was cancelled
 *
 * Additionally, the `content` state has a `refresh` method that can be used to
 * refresh the request in the background, which is available as a sub-state of
 * the `content` state.
 *
 * ### Example Usage
 *
 * ```tsx
 * import { Request } from "@warp-drive/react";
 *
 * export function UserPreview($props: { id: string | null }) {
 *   return (
 *    <Request
 *       query={findRecord('user', $props.id)}
 *       states={{
 *         idle: () => <div>Waiting for User Selection</div>,
 *         loading: ({ state }) => <div>Loading user data...</div>,
 *         cancelled: ({ error, features }) => (
 *           <div>
 *             <p>Request Cancelled</p>
 *             <p><button onClick={features.retry}>Start Again?</button></p>
 *           </div>
 *         ),
 *         error: ({ error, features }) => (
 *           <div>
 *             <p>Error: {error.message}</p>
 *             <p><button onClick={features.retry}>Try Again?</button></p>
 *           </div>
 *         ),
 *         content: ({ result, features }) => (
 *           <div>
 *            <h2>User Details</h2>
 *            <p>ID: {result.id}</p>
 *            <p>Name: {result.name}</p>
 *          </div>
 *        ),
 *      }}
 *    />
 *   );
 * }
 *
 * ```
 *
 */
export function Request<RT, E>($props: RequestProps<RT, E>): JSX.Element {
  return (
    <ReactiveContext>
      <InternalRequest {...$props} />
    </ReactiveContext>
  );
}

function InternalRequest<RT, E>($props: RequestProps<RT, E>): JSX.Element {
  const store = $props.store ?? useStore();
  const Chrome = $props.chrome ?? DefaultChrome;
  const sink = useRef<RequestSubscription<RT, E> | null>(null);
  const args = useRef<SubscriptionArgs<RT, E> | null>(null);

  if (!args.current) {
    args.current = new ReactiveArgs<RT, E>();
  }
  Object.assign(args.current, $props);

  if (sink.current && (sink.current.store !== store || $props.subscription)) {
    sink.current[DISPOSE]();
    sink.current = null;
  }

  if (!sink.current && !$props.subscription) {
    sink.current = createRequestSubscription(store, args.current!);
  }

  const initialized = useRef<null | { disposable: { [DISPOSE]: () => void } | null; dispose: () => void }>(null);
  useEffect(() => {
    if (sink.current && (!initialized.current || initialized.current.disposable !== sink.current)) {
      initialized.current = {
        disposable: sink.current,
        dispose: () => {
          sink.current?.[DISPOSE]();
          initialized.current = null;
          sink.current = null;
        },
      };
    }

    return sink.current ? initialized.current!.dispose : undefined;
  }, [sink.current]);

  const state = $props.subscription ?? sink.current!;
  const slots = $props.states;

  console.log({
    state,
    slots,
  });

  return (
    <Chrome state={state.isIdle ? null : state.reqState} features={state.contentFeatures}>
      {
        // prettier-ignore
        state.isIdle && slots.idle ? <slots.idle />
          : state.isIdle ? <Throw error={IdleBlockMissingError} />
          : state.reqState.isLoading ? slots.loading ? <slots.loading state={state.reqState.loadingState} /> : ''
          : state.reqState.isCancelled && slots.cancelled ? <slots.cancelled error={state.reqState.reason} features={state.errorFeatures} />
          : state.reqState.isError && slots.error ? <slots.error error={state.reqState.reason} features={state.errorFeatures} />
          : state.reqState.isSuccess ? slots.content ? <slots.content result={state.reqState.value} features={state.contentFeatures} /> : <Throw error={new Error('No content block provided for <Request> component.')} />
          : !state.reqState.isCancelled ? <Throw error={state.reqState.reason} />
          : '' // never
      }
    </Chrome>
  );
}

// warp-drive-packages/svelte/src/lib/request.svelte
<!--
  The `<Request />` component is a powerful tool for managing data fetching and
  state in your Svelte application. It provides a declarative approach to reactive
  control-flow for managing requests and state in your application.

  The `<Request />` component is ideal for handling "boundaries", outside which some
  state is still allowed to be unresolved and within which it MUST be resolved.

  ## Request States

  `<Request />` has five states, only one of which will be active and rendered at a time.

  - `idle`: The component is waiting to be given a request to monitor
  - `loading`: The request is in progress
  - `error`: The request failed
  - `content`: The request succeeded
  - `cancelled`: The request was cancelled

  ## Usage Example

  ```svelte
  <script>
    import { Request } from '@warp-drive/svelte';
    import { getStore } from '$lib/context/store.svelte';

    const store = getStore();
    let request = store.request(someQuery);
  </script>

  <Request {request}>
    {#snippet loading(state)}
      <Spinner percentDone={state.completedRatio} />
      <button onclick={state.abort}>Cancel</button>
    {/snippet}

    {#snippet error(error, features)}
      <ErrorForm {error} />
      <button onclick={features.retry}>Retry</button>
    {/snippet}

    {#snippet content(data, features)}
      <h1>{data.title}</h1>
      {#if features.isRefreshing}
        <SmallSpinner />
        <button onclick={features.abort}>Cancel</button>
      {:else}
        <button onclick={features.refresh}>Refresh</button>
      {/if}
    {/snippet}

    {#snippet cancelled(error, features)}
      <h2>The Request was cancelled</h2>
      <button onclick={features.retry}>Retry</button>
    {/snippet}

    {#snippet idle()}
      <button onclick={kickOffRequest}>Load Preview?</button>
    {/snippet}
  </Request>
  ```

  ## Autorefresh

  `<Request />` supports automatic refresh and reload under certain conditions:

  - `online`: This occurs when a browser window or tab comes back to the foreground
    after being backgrounded or when the network reports as being online after
    having been offline.
  - `interval`: This occurs when a specified amount of time has passed.
  - `invalid`: This occurs when the store emits a notification that the request
    has become invalid.

  You can specify when autorefresh should occur by setting the `autorefresh` prop
  to `true` or a comma-separated list of the above values.

  A value of `true` is equivalent to `'online,invalid'`.
-->

<script lang="ts" generics="RT, T, E">
  import { getContext, onDestroy } from 'svelte';
  import type { Store, StoreRequestInput } from '@warp-drive/core';
  import { assert } from '@warp-drive/core/build-config/macros';
  import type { Future } from '@warp-drive/core/request';
  import type { RequestLoadingState, RequestState, RequestSubscription } from '@warp-drive/core/store/-private';
  import { createRequestSubscription, DISPOSE } from '@warp-drive/core/store/-private';
  import type { StructuredErrorDocument } from '@warp-drive/core/types/request';
  import type { Snippet } from 'svelte';
  import type { AutorefreshBehaviorCombos, ContentFeatures, RecoveryFeatures } from './types';

  interface Props<RT, T, E> {
    /**
     * The request to monitor. This should be a `Future` instance returned
     * by either the `store.request` or `store.requestManager.request` methods.
     */
    request?: Future<RT>;

    /**
     * A query to use for the request. This should be an object that can be
     * passed to `store.request`. Use this in place of `request` if you would
     * like the component to also initiate the request.
     */
    query?: StoreRequestInput<RT, T>;

    /**
     * The store instance to use for making requests. If contexts are available,
     * the component will default to using the `store` on the context.
     *
     * This is required if the store is not available via context or should be
     * different from the store provided via context.
     */
    store?: Store;

    /**
     * The autorefresh behavior for the request. This can be a boolean, or any
     * combination of the following values: `'online'`, `'interval'`, `'invalid'`.
     *
     * - `'online'`: Refresh the request when the browser comes back online
     * - `'interval'`: Refresh the request at a specified interval
     * - `'invalid'`: Refresh the request when the store emits an invalidation
     *
     * If `true`, this is equivalent to `'online,invalid'`.
     *
     * Defaults to `false`.
     */
    autorefresh?: AutorefreshBehaviorCombos;

    /**
     * The number of milliseconds to wait before refreshing the request when the
     * browser comes back online or the network becomes available.
     *
     * This also controls the interval at which the request will be refreshed if
     * the `interval` autorefresh type is enabled.
     *
     * Defaults to `30_000` (30 seconds).
     */
    autorefreshThreshold?: number;

    /**
     * The behavior of the request initiated by autorefresh. This can be one of
     * the following values:
     *
     * - `'refresh'`: Refresh the request in the background
     * - `'reload'`: Force a reload of the request
     * - `'policy'` (**default**): Let the store's configured CachePolicy decide whether to
     *    reload, refresh, or do nothing.
     *
     * Defaults to `'policy'`.
     */
    autorefreshBehavior?: 'refresh' | 'reload' | 'policy';

    /**
     * The block to render when the component is idle and waiting to be given a request.
     */
    idle?: Snippet;

    /**
     * The block to render when the request is loading.
     */
    loading?: Snippet<[state: RequestLoadingState]>;

    /**
     * The block to render when the request was cancelled.
     */
    cancelled?: Snippet<[
      /**
       * The Error the request rejected with.
       */
      error: StructuredErrorDocument<any>,
      /**
       * Utilities to assist in recovering from the error.
       */
      features: RecoveryFeatures,
    ]>;

    /**
     * The block to render when the request failed. If this block is not provided,
     * the error will be rethrown.
     *
     * Thus it is required to provide an error block and proper error handling if
     * you do not want the error to crash the application.
     */
    error?: Snippet<[
      /**
       * The Error the request rejected with.
       */
      error: StructuredErrorDocument<E>,
      /**
       * Utilities to assist in recovering from the error.
       */
      features: RecoveryFeatures,
    ]>;

    /**
     * The block to render when the request succeeded.
     */
    content?: Snippet<[value: RT, features: ContentFeatures<RT>]>;

    /**
     * The always block that receives the current state
     */
    always?: Snippet<[state: RequestState<RT, T, StructuredErrorDocument<E>>]>;
  }

  let {
    request,
    query,
    store: providedStore,
    autorefresh,
    autorefreshThreshold,
    autorefreshBehavior,
    idle,
    loading,
    cancelled,
    error,
    content,
    always,
  }: Props<RT, T, E> = $props();

  const contextStore = getContext<Store>('store');

  function throwError(error: any): never {
    throw error;
  }

  function notNull(x: null): never;
  function notNull<T>(x: T): Exclude<T, null>;
  function notNull<T>(x: T | null) {
    assert('Expected a non-null value, but got null', x !== null);
    return x;
  }

  const IdleBlockMissingError = new Error(
    'No idle block provided for <Request> component, and no query or request was provided.'
  );

  const resolvedStore = $derived.by(() => {
    const store = providedStore || contextStore
    assert(
      `No store was provided to the <Request> component. Either provide a store via the store prop or via the context API.`,
      store
    );
    return store;
  });

  let _state: RequestSubscription<RT, T, E> | null = null;

  const state = $derived.by(() => {
    if (_state && (_state as any).store !== resolvedStore) {
      _state[DISPOSE]();
      _state = null;
    }

    if (!_state) {
      _state = createRequestSubscription(resolvedStore, {
        request,
        query,
        autorefresh,
        autorefreshThreshold,
        autorefreshBehavior,
      });
    }

    return _state;
  });

  const isIdle = $derived(state?.isIdle ?? true);
  const reqState = $derived(state?.reqState);
  const result = $derived(state?.result);
  const errorFeatures = $derived(state?.errorFeatures);
  const contentFeatures = $derived(state?.contentFeatures);

  onDestroy(() => {
    if (_state) {
      _state[DISPOSE]();
      _state = null;
    }
  });
</script>

{#if isIdle}
  {#if idle}
    {@render idle()}
  {:else}
    {throwError(IdleBlockMissingError)}
  {/if}
{:else if reqState?.isLoading}
  {#if loading}
    {@render loading(reqState.loadingState)}
  {/if}
{:else if reqState?.isCancelled}
  {#if cancelled}
    {@render cancelled(notNull(reqState.reason), errorFeatures)}
  {/if}
{:else if reqState?.isError}
  {#if error}
    {@render error(notNull(reqState.reason), errorFeatures)}
  {:else}
    {throwError(notNull(reqState.reason))}
  {/if}
{:else if reqState?.isSuccess}
  {#if content}
    {@render content(result, contentFeatures)}
  {/if}
{:else if reqState && !(reqState as any).isCancelled}
  {throwError(notNull((reqState as any).reason))}
{/if}

{#if always && reqState}
  {@render always(reqState)}
{/if}
